language: rust
os:
  - linux
rust:
  - stable
cache: cargo # cache cargo-audit once installed
matrix:
  fast_finish: true
before_script:
  - cargo install --force cargo-audit
  - cargo generate-lockfile
script:
  - cargo audit
