# The language to output bindings in
language = "C"
include_guard = "ADBLOCK_RUST_FFI_H"

[parse]
# Whether to parse dependent crates and include their types in the generated
# bindings
parse_deps = true
# A black list of crate names that are not allowed to be parsed
include = ["adblock"]

[parse.expand]
# A list of crate names that should be run through `cargo expand` before
# parsing to expand any macros
# crates = ["adblock-ffi"]
crates = []
all_features = false
default_features = false
features = ["cbindgen"]

[export]
# A prefix to add before the name of every item
prefix = "C_"

[defines]
"feature = embedded-domain-resolver" = "EMBEDDED_DOMAIN_RESOLVER"
